mkdir Videoteca/
cd Videoteca/
mkdir -p Aventura/Dune
cd Aventura/Dune
echo "A mythic and emotionally charged hero's journey, "'"Dune"'" tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, who must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive." > "Dune 8.2 IMDb".txt
cd ..
cd ..
mkdir -p Romance/"Call Me By Your Name"
cd Romance/"Call Me By Your Name"
echo "CALL ME BY YOUR NAME, the new film by Luca Guadagnino, is a sensual and transcendent tale of first love, based on the acclaimed novel by André Aciman. It's the summer of 1983 in the north of Italy, and Elio Perlman (Timothée Chalamet), a precocious 17-year-old young man, spends his days in his family's 17th-century villa transcribing and playing classical music, reading, and flirting with his friend Marzia (Esther Garrel). Elio enjoys a close relationship with his father (Michael Stuhlbarg), an eminent professor specializing in Greco-Roman culture, and his mother Annella (Amira Casar), a translator, who favor him with the fruits of high culture in a setting that overflows with natural delights. While Elio's sophistication and intellectual gifts suggest he is already a fully-fledged adult, there is much that yet remains innocent and unformed about him, particularly about matters of the heart. One day, Oliver (Armie Hammer), a 24-year-old American college graduate student working on his doctorate, arrives as the annual summer intern tasked with helping Elio's father. Amid the sun-drenched splendor of the setting, Elio and Oliver discover the heady beauty of awakening desire over the course of a summer that will alter their lives forever." > "Call Me By Your Name 7.9 IMDb".txt
cd ..
cd ..
mkdir -p Documentario/"David Attenborough: A Life on Our Planet"
cd Documentario/"David Attenborough: A Life on Our Planet"
echo "One man has seen more of the natural world than any other. This unique feature documentary is his witness statement. In his 93 years, David Attenborough has visited every continent on the globe, exploring the wild places of our planet and documenting the living world in all its variety and wonder. Now, for the first time he reflects upon both the defining moments of his lifetime as a naturalist and the devastating changes he has seen. Honest, revealing and urgent, DAVID ATTENBOROUGH: A LIFE ON OUR PLANET is a powerful first-hand account of humanity's impact on nature and a message of hope for future generations. Created by award-winning natural history filmmakers Silverback Films and global conservation organization WWF, the film is Directed by Alastair Fothergill, Jonnie Hughes and Keith Scholey and Executive Produced by Colin Butfield. Celebrated British naturalist Sir David Attenborough has a broadcasting career spanning over eight decades. He has visited every continent on the globe, exploring the wild places of our planet and bringing the wonders of the living world to audiences worldwide through groundbreaking natural history series. His work includes: Life on Earth, Planet Earth and more recently the Netflix original documentary series Our Planet." > "David Attenborough: A Life on Our Planet 9.0 IMDb".txt
